openapi: 3.0.0
info:
  title: Sber "beautifulcode" brackets punctuation checker service
  version: 1.0.0
paths:
  /api/checkBrackets:
    post:
      summary: Check brackets balance in text
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CheckBracketsRequest'
      responses:
        '200':
          description: Brackets checked result
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CheckBracketsResponse'
        '400':
          description: Illegal request or input text
components:
  schemas:
    CheckBracketsRequest:
      type: object
      required:
        - text
      properties:
        text:
          type: string
          minLength: 1
    CheckBracketsResponse:
      type: object
      required:
        - isCorrect
      properties:
        isCorrect:
          type: boolean
